spring:
  application:
    name: consumer
  cloud:
    config:
      uri: ${config.server.url:http://config-server/}
      label: master
      profile: ${spring.profiles.active:dev}
      fail-fast: true
      retry:
        initial-interval: 20000
        max-attempts: 6
    loadbalancer:
      retry:
        enabled: true

server:
  port: 8765
  servlet:
    context-path: /consumer

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    enabled: true

