server:
  port: 8765

spring:
  application:
    name: consumer
  cloud:
    config:
      label: ${run.label:master}
      url: ${config.server.url:http://config-server:8888/}
      profile: dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


feign:
  hystrix:
    enabled: true

