eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8769
spring:
  application:
    name: gateway-zuul

zuul:
  routes:
    order:
      path: /order/**
      serviceId: order
    consumer:
      path: /consumer/**
      serviceId: consumer
    product:
      path: /product/**
      serviceId: product