eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8769
spring:
  application:
    name: gateway-zuul

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: order
    api-b:
      path: /api-b/**
      serviceId: consumer