server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        native:
          search-locations: classpath:/native
        git:
          uri: https://github.com/peintune/springcloud-study
          search-paths: config-server/src/main/resources/repo
          username:
          password: